### ISSUE TITLE
MissingKeyException on Filter and Group

### ISSUE THREAD

**Issue by cubed-it** [RolandPheasant/DynamicData#59] opened 2016-10-27 10:32 UTC
Hi there,

first of all, thanks for your great work. Looks like an amazing useful utility and I would love to integrate it in some parts of my application. Unfortunately, on my first test I run into an issue with grouping and filtering.
So here is what I try to do:
1)	A SourceCache is filled from a Service. Items are only added so far.
2)	After the Connect I apply a Filter and then I Group the data.
3)	The Filter may change and additional data may be added.
But now I run into MissingKeyException("{0} is missing from previous value on remove. Object type {1}, Key type {2}, Group key type {3}" in my big Application.
I created a little Test Project and there I have the same issue. At least it looks like, because in my big application it also crashed when the SourceCache is not changed. Just starting Edit and doing a loop inside makes the difference. If I do not call Edit after changing the filter it does work. Also it does "work" if I throttle 250ms before and after the Filter part...
However, here is the sample. Hope you could help me with that and tell my what I'm doing wrong here... Thanks!

```
public sealed partial class MainPage : Page
   {
      private SourceCache<TestObject, int> m_sourceCache;
      private ReplaySubject<Func<TestObject, bool>> m_changeObs;
      private ReadOnlyObservableCollection<GroupContainer> m_entries;
      public ReadOnlyObservableCollection<GroupContainer> Entries => m_entries;

      public MainPage()
      {
         this.InitializeComponent();

         m_changeObs = new ReplaySubject<Func<TestObject, bool>>();

         var dispatcher = new CoreDispatcherScheduler(Window.Current.Dispatcher);

         m_sourceCache = new SourceCache<TestObject, int>(x => x.Id);
         m_sourceCache.Connect()
            .Filter(m_changeObs)
            .Group(x => x.Group)
            .Transform(x => new GroupContainer(x, dispatcher))
            .ObserveOn(dispatcher)
            .Bind(out m_entries)
            .Subscribe();

         Observable.Interval(TimeSpan.FromMilliseconds(250))
            .Subscribe(x => DoFilterAndAdd());
      }

      private int m_count;
      private void AddItems()
      {
         m_sourceCache.Edit(innerCache =>
         {
            var list = new List<TestObject>();
            for (var i = 0; i < 10; i++)
            {
               m_count++;
               list.Add(new TestObject() {Id = m_count, Group = i, Text = DateTime.Now.ToString("T")});
            }
            innerCache.AddOrUpdate(list);
         });
      }

      private bool m_bool;
      private void DoFilterAndAdd()
      {
         m_bool = !m_bool;
         m_changeObs.OnNext(o => m_bool);
         AddItems();
      }
   }

   public class TestObject
   {
      public int Id { get; set; }

      public string Text { get; set; }

      public int Group { get; set; }
   }

   public class GroupContainer
   {
      private readonly ReadOnlyObservableCollection<GroupEntry> m_entries;
      
      public ReadOnlyObservableCollection<GroupEntry> Entries => m_entries;

      public GroupContainer(IGroup<TestObject, int, int> groupEntries, IScheduler scheduler)
      {
         groupEntries.Cache.Connect()
                                 .Transform(x => (new GroupEntry(x)))
                                 .ObserveOn(scheduler)
                                 .Bind(out m_entries)
                                 .Subscribe();
         Title = groupEntries.Key.ToString("D");
      }
      public string Title { get; set; }
      
   }

   public class GroupEntry
   {
      public string Title { get; set; }

      public GroupEntry(TestObject obj)
      {
         Title = obj.Text;
      }
   }
```

**Comment by RolandPheasant** [comment] 2016-10-27 10:48
Are you using v5?  The reason I ask is the same problem has previously been reported and solved. 

The only reason  a key can be missing is due to a threading issue.  I will double check the locking when the filter is applied

**Comment by cubed-it** [comment] 2016-10-27 10:50
Hey, that was fast 👍 
I'am using "DynamicData": "5.0.4.2075",

**Comment by RolandPheasant** [comment] 2016-10-27 13:29
I've got it.  It turns out the filter was holding on to some state which should have been cleared. This was inadvertently introduced by a recent optimisation

**Comment by RolandPheasant** [comment] 2016-10-27 13:43
@cubed-it it should be fixed now. The fix is here [DynamicData v5.0.5.2078](https://www.nuget.org/packages/DynamicData/5.0.5.2078). Please use that version and let me know if the problem has gone.

**Closed** 2016-10-27 15:20 UTC
Labels: bug

**Comment by cubed-it** [comment] 2016-10-27 20:49
Sounds great. I will take a look at work tomorrow and let you know.
Thanks alot for the very quick fix!

**Comment by cubed-it** [comment] 2016-10-28 06:46
Good Morning,
now it works as expected. 
Thanks again and have a nice day!

**Comment by RolandPheasant** [comment] 2016-10-28 07:06
Cool. Any questions feel free to ask on [DynamicData on gitter](https://gitter.im/RolandPheasant/DynamicData)

**Comment by crosscourt** [comment] 2017-11-01 02:22
I got the MissingKey Exception in v5.4.1.2196

**Comment by RolandPheasant** [comment] 2017-11-01 07:20
Do you get this repeatedly and any idea how it can be replicated in test code?

**Comment by crosscourt** [comment] 2017-11-01 08:30
Unfortunately I'm not sure how to reproduce it but it does happen once per day.

We do a cache.Edit(u => u.Update(x)) in a background thread.
u.Update(x) triggers a subscriber cache.Connect().WhereReasonsAre(...).Group(x => x.GroupKey).Transform().Subscribe(o => {}, e => {error logged here})

**Comment by RolandPheasant** [comment] 2017-11-01 09:34
This is due to filtering the reasons. There are several ways to work around this. I will I have think about the best solution and get back to you.
