### ISSUE TITLE
Filtering becomes mighty slow when applied to a large collection

### ISSUE THREAD

**Issue by mmalek06** [RolandPheasant/DynamicData#97] opened 2017-10-25 16:23 UTC
Using this code:

```
var list = new SourceList<int>();
var totalCount = 0;

list.Connect().Filter(v => v % 2 == 0).Subscribe(v =>
{
	totalCount++;

	if (totalCount % 1000 == 0)
	{
		Console.Write(".");
	}
});

for (int i = 0; i < 1000000; i++)
{
	list.Add(i);
}

Console.WriteLine($"\nTotal count {totalCount}");
```

We can see that the performence drastically deteriorates and it's a very quick process. We tracked it down to the ListEx class, specifically to the EnsureCapacityFor method and your strategy of increasing the list capacity. We fixed it by doing this:

```
public static void EnsureCapacityFor<T>(this IEnumerable<T> source, IChangeSet changes)
{
	if (source == null) throw new ArgumentNullException(nameof(source));
	if (changes == null) throw new ArgumentNullException(nameof(changes));
	if (source is List<T>)
	{
		var list = (List<T>)source;

		if (list.Count + changes.Adds > list.Capacity)
			list.Capacity *= 2;
	}
	else if (source is ISupportsCapcity)
	{
		var list = (ISupportsCapcity)source;

		if (list.Count + changes.Adds > list.Capacity)
			list.Capacity *= 2;
	}
	else if (source is IChangeSet)
	{
		var original = (IChangeSet)source;

		if (original.Count + changes.Count > original.Capacity)
			original.Capacity *= 2;
	}
}

```

So here we are just doubling the capacity. The other problem is that we experience the same perf issue with the SourceCache class. We can change it on our own and just use a custom version of your library, but it would be probably better for everyone if you would implement a fix for it :P.

**Comment by RolandPheasant** [comment] 2017-10-25 16:40
First of all, I am interested in your fix. Anything which improves performance is always welcome.  Would you be happy to raise a PR? 

The sample code will always be prone to  slowness because each time you call ```List.Add``` a new change set is created and the evaluation of the operators in the chain are repeatedly applied.  I always recommend where possible to batch the input for loading the collection, but of course this is not always desirable.

Out of interest, is there any reason why you cannot just use ```list.AddRange(1000000)``` ?

**Comment by RolandPheasant** [comment] 2017-10-25 17:02
I just tried your fix locally and I can see a huge difference.

However I also wonder why it was that I added that code in the first place.  I think it was an early attempt to improve performance on list data.  So I decided to comment out the code altogether and I was surprised to find out that the result was marginally quicker.  I will scrutinise the code further.

**Comment by mmalek06** [comment] 2017-10-25 17:18
As for your first comment - yes, I can create a pull request, but I wanted to first consult with you :). As for why I didn't use AddRange method - it was just a sample. The real problem we have is on our dev environment - we load a bunch of events from a stream in EventStore into memory, and later we filter, page, etc. Anyway - in the real application the cache is first populated and only then it's subscribed to and this problem persists, so it's not about using unoptimized approach I think. Also in the real application we're using SourceCache, not SourceList, but I guess they are related the way that both have horrible filter performance when there's lots of data in it. I didn't have time to look into the SourceCache today, but I'm 100% sure the problem is caused by something similar there.

**Comment by RolandPheasant** [comment] 2017-10-25 17:26
I think for the List we can dispense with EnsureCapacityFor() altogether.   I will be interested to hear your findings on the cache side of things.

**Comment by RolandPheasant** [comment] 2017-10-26 08:23
I got rid of EnsureCapacityFor() and used [this code](https://gist.github.com/RolandPheasant/11bb56dd0ef110dec3dde4bc77e120f7) to get some quick benchmarks.

Not a perfect measure but gives a good idea

![image](https://user-images.githubusercontent.com/9879866/32042336-1694d19c-ba2f-11e7-8f48-4ae8e8bd4fb7.png)

**Comment by alexgula** [comment] 2017-10-26 08:52
Btw, thank you, @RolandPheasant for the great idea and library, it changed our approach drastically and allowed to clean up a lot of code!

**Comment by RolandPheasant** [comment] 2017-11-09 20:20
@mmalek06 I have spent some time dealing with observable list performance issues. And here are the latest measures:

![image](https://user-images.githubusercontent.com/9879866/32626519-781aee98-c587-11e7-8fd2-5e08b73f1e91.png)

Considering that the version before I remove EnsureCapacity() practically ground to a halt with 1M successive updates, I would say these results have fixed the issue. Now I will turn my attention to the observable cache (I have already done some optimisations) and check the timings.

I take performance seriously as can be seen by me spending 2 weeks fine tuning the observable list since this issue was raised.  However Dynamic Data was never designed do deal with scenarios where data is loaded as individual items in rapid succession. It was designed from the beginning with the concept to load data up front in a single batch and then process async updates as they arrive.  If the data is not handled as a collection and instead every individual item handled in isolation then surely standard rx without the overheads of creating change sets to transmit changes would be a better option.

If you cannot control the input of the source then buffering tends to improve performance greatly. For 
example a simple buffer on the input or dynamic data source 

To buffer all updates, you can do this
```
list.Connect()
   .Buffer(TimeSpan.FromMilliseconds(250)).FlattenBufferResult() ;
````

Or for scenarios where only initial data is buffered an extension like this would help

```
  //After the first item of data arrives buffer for the specified period of time, 
  //After the initial buffer is complete stop buffering and process updates without buffering
    public static IObservable<IChangeSet<T>> BufferInitial<T>(this IObservable<IChangeSet<T>> source, TimeSpan initalBuffer, IScheduler scheduler = null)
    {
        return source.DeferUntilLoaded().Publish(shared =>
        {
            var initial = shared.Buffer(initalBuffer, scheduler ?? Scheduler.Default)
                .FlattenBufferResult()
                .Take(1);

            return initial.Concat(shared);
        });
    }
```

example usage:

```
list.Connect()
    .BufferInitial(TimeSpan.FromMilliseconds(250), sheduler)
```

**Comment by mmalek06** [comment] 2017-11-23 09:48
Thanks Roland! We are really eager to check out your next changes to the observable cache stuff :)

**Comment by RolandPheasant** [comment] 2017-11-23 21:50
I have released v6. If you are using v5 you should be easily able to upgrade.

**Comment by RolandPheasant** [comment] 2017-11-24 06:00
Btw I also added the BufferInital operator to the library

**Closed** 2018-03-19 22:06 UTC
